-- =============================================================================
-- GIF Schema — Migration 007
-- User-to-persona identity binding: verification token columns.
--
-- Applies to: gif database
-- Run as: psql -U postgres -d gif -f gif/schema/007_identity_binding.sql
--
-- Sprint 5: Compliance Hardening — Deliverable 2
--
-- Covers:
--   1. Add token lifecycle columns to gif.user_persona_assignments
--   2. Enable RLS on user_persona_assignments with consume-only UPDATE policy
--   3. Column-level UPDATE grant for token consumption only
--
-- Design rationale (see ADR-021, Sprint 5 plan):
--   Every persona creation should be traceable to an individually authenticated
--   human admin. The mechanism: an HMAC-SHA-256 signed token generated by the
--   issue_identity_token CLI, passed to persona_create, verified in the
--   enforcement engine, and consumed (one-time use).
--
--   verified_identity_ref: optional human-readable identity annotation the
--   admin records when creating the assignment (e.g. 'github:scottrhodes').
--   Not validated by GIF — informational only (ADR-021: no users table in GIF).
--
--   token_consumed: one-way flag. RLS policy ensures gif_app can only
--   UPDATE rows from token_consumed=false to token_consumed=true — reversal
--   is impossible through the application user.
-- =============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- PART 1: Add token lifecycle columns to user_persona_assignments
-- ---------------------------------------------------------------------------

ALTER TABLE gif.user_persona_assignments
    ADD COLUMN IF NOT EXISTS verified_identity_ref  VARCHAR(255),
    -- Optional human-readable identity annotation recorded by the admin at
    -- assignment creation time. Not validated — informational reference only.
    -- Examples: 'github:scottrhodes', 'admin-account-1', 'google:admin@example.com'

    ADD COLUMN IF NOT EXISTS identity_provider_hint VARCHAR(100),
    -- Optional. Short label for the identity system this assignment references.
    -- Examples: 'local-admin', 'github', 'google-workspace', 'okta'
    -- Not validated by GIF — informational only (ADR-021).

    ADD COLUMN IF NOT EXISTS token_consumed         BOOLEAN NOT NULL DEFAULT false,
    -- Set to true when an HMAC token for this assignment has been used to
    -- authorize a persona_create call. Single-use — cannot be reset to false
    -- via application user (enforced by RLS policy below).

    ADD COLUMN IF NOT EXISTS token_consumed_at      TIMESTAMP WITH TIME ZONE;
    -- Timestamp when the token was consumed. Null while token_consumed = false.

COMMENT ON COLUMN gif.user_persona_assignments.verified_identity_ref IS
    'Optional admin-written identity annotation at assignment creation time. '
    'Examples: ''github:scottrhodes'', ''admin-account-1''. '
    'Not validated by GIF — informational reference per ADR-021.';

COMMENT ON COLUMN gif.user_persona_assignments.identity_provider_hint IS
    'Optional label for the identity system this assignment references. '
    'Not validated by GIF — informational per ADR-021.';

COMMENT ON COLUMN gif.user_persona_assignments.token_consumed IS
    'True when the identity token for this assignment has been used in a '
    'persona_create call. Single-use. RLS enforces one-way transition only: '
    'false → true. Application user cannot reset to false.';

COMMENT ON COLUMN gif.user_persona_assignments.token_consumed_at IS
    'Timestamp of token consumption. Non-null iff token_consumed = true.';

-- Consistency constraint: consumed state and timestamp must agree
ALTER TABLE gif.user_persona_assignments
    ADD CONSTRAINT upa_token_consumed_consistent CHECK (
        (token_consumed = false AND token_consumed_at IS NULL) OR
        (token_consumed = true  AND token_consumed_at IS NOT NULL)
    );

-- ---------------------------------------------------------------------------
-- PART 2: Enable RLS on user_persona_assignments
--
-- Previously no RLS — SELECT and INSERT were granted via standard GRANTs.
-- Enabling RLS requires explicit SELECT and INSERT policies to preserve
-- existing behaviour. The new UPDATE policy is the key addition: it enforces
-- one-way token consumption only.
-- ---------------------------------------------------------------------------

ALTER TABLE gif.user_persona_assignments ENABLE ROW LEVEL SECURITY;

-- gif_app policies
CREATE POLICY upa_select_gif_app
    ON gif.user_persona_assignments AS PERMISSIVE FOR SELECT TO gif_app
    USING (true);

CREATE POLICY upa_insert_gif_app
    ON gif.user_persona_assignments AS PERMISSIVE FOR INSERT TO gif_app
    WITH CHECK (true);

-- Consume-only UPDATE for gif_app:
--   USING: only rows where token_consumed is currently false can be updated.
--   WITH CHECK: the result must have token_consumed = true and timestamp set.
--   Effect: gif_app can only flip false → true, never true → false.
CREATE POLICY upa_consume_token_gif_app
    ON gif.user_persona_assignments AS PERMISSIVE FOR UPDATE TO gif_app
    USING (token_consumed = false)
    WITH CHECK (token_consumed = true AND token_consumed_at IS NOT NULL);

-- ---------------------------------------------------------------------------
-- PART 3: Column-level UPDATE grant
--
-- Standard table-level GRANTs for gif_app on this table are SELECT, INSERT
-- only (migration 005). Column-level UPDATE grant is required for the consume
-- operation. Restricted to the two token lifecycle columns only.
-- Adopter layer users (research_app, etc.) are granted equivalent access by
-- their own bootstrap scripts.
-- ---------------------------------------------------------------------------

GRANT UPDATE (token_consumed, token_consumed_at)
    ON gif.user_persona_assignments TO gif_app;

-- ---------------------------------------------------------------------------
-- Verify
-- ---------------------------------------------------------------------------

DO $$
DECLARE
    col_count   INTEGER;
    rls_enabled BOOLEAN;
    pol_count   INTEGER;
BEGIN
    SELECT count(*) INTO col_count
    FROM information_schema.columns
    WHERE table_schema = 'gif'
      AND table_name   = 'user_persona_assignments'
      AND column_name  IN ('verified_identity_ref', 'identity_provider_hint',
                           'token_consumed', 'token_consumed_at');

    IF col_count <> 4 THEN
        RAISE EXCEPTION 'Expected 4 new columns on user_persona_assignments, found %', col_count;
    END IF;

    SELECT relrowsecurity INTO rls_enabled
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.relname = 'user_persona_assignments' AND n.nspname = 'gif';

    IF NOT rls_enabled THEN
        RAISE EXCEPTION 'RLS not enabled on gif.user_persona_assignments';
    END IF;

    SELECT count(*) INTO pol_count
    FROM pg_policies
    WHERE schemaname = 'gif' AND tablename = 'user_persona_assignments';

    -- 3 policies: SELECT/INSERT/UPDATE for gif_app
    -- Adopter layer users add their own policies via their bootstrap scripts
    IF pol_count <> 3 THEN
        RAISE EXCEPTION 'Expected 3 RLS policies on user_persona_assignments, found %', pol_count;
    END IF;

    RAISE NOTICE 'Migration 007 verified: % new columns, RLS enabled, % policies', col_count, pol_count;
END;
$$;

COMMIT;
